### ISSUE TITLE
Update ION DAO images

### ISSUE THREAD

**Issue by gnujoow** [osmosis-labs/apps-list#22]
![image (2)](https://github.com/osmosis-labs/apps-list/assets/10865414/772956bc-dfc4-48d2-94e4-c75e03f5a47e)
![image (1)](https://github.com/osmosis-labs/apps-list/assets/10865414/5f6fbfce-c09a-4bf0-bbf5-26f5eb3692cc)

https://github.com/osmosis-labs/apps-list/blob/a634bd143e4f9ea7358bc1f4ed1795eba12e99e3/applications.json#L3-L13

**Comment by JeremyParish69** [comment]
Resolved by https://github.com/osmosis-labs/apps-list/pull/24
